import type { MockProduct } from "../petwise";

export const staticRealProducts: MockProduct[] = [
  {
    id: "hills-science-diet-adult-dog-chicken-barley",
    name: "Science Diet Adult Chicken & Barley Recipe Dog Food",
    brand: "Hill's Science Diet",
    retailer: "Hill's Pet Nutrition",
    productUrl: "https://www.hillspet.com/dog-food/science-diet-adult-original-dry",
    species: "dog",
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness", "picky_eating"],
    excludedIngredients: ["chicken", "grains"],
    avoidIngredientKeywords: ["chicken", "chicken meal", "barley", "grain"],
    ingredientHighlights: ["Chicken", "Barley"],
    lifeStage: "adult",
    tags: ["dry food", "adult", "chicken", "nutrition"],
    currency: "USD",
    active: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt: "2026-07-13",
    sourceNote: "Official Hill's product page.",
    whyItFits:
      "A real adult dog food option for nutrition comparisons when the profile supports looking at food.",
    whyCategoryFits:
      "Food is only shown when Furvise has a nutrition reason or the owner selected a nutrition goal.",
    cautions:
      "Contains chicken and grains. Transition foods gradually and ask a veterinarian about medical diets or health concerns.",
  },
  {
    id: "purina-cat-chow-complete-chicken",
    name: "Cat Chow Complete High Protein Dry Cat Food With Real Chicken",
    brand: "Purina Cat Chow",
    retailer: "Purina",
    productUrl: "https://www.purina.com/cats/shop/cat-chow-complete-dry-cat-food",
    species: "cat",
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness", "picky_eating"],
    excludedIngredients: ["chicken", "grains"],
    avoidIngredientKeywords: ["chicken", "corn", "wheat", "soy", "fish meal"],
    ingredientHighlights: ["Chicken", "Corn", "Wheat", "Soy", "Fish meal"],
    lifeStage: "all",
    tags: ["dry food", "cat", "chicken", "nutrition"],
    currency: "USD",
    active: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt: "2026-07-13",
    sourceNote: "Official Purina product page.",
    whyItFits:
      "A real cat food option for nutrition comparisons when the profile supports looking at food.",
    whyCategoryFits:
      "Cat food is shown only for cat profiles and only when nutrition context supports product comparison.",
    cautions:
      "Contains chicken, corn, wheat, soy, and fish meal. Transition foods gradually and check the label for current ingredients.",
  },
  {
    id: "hills-science-diet-adult-cat-chicken",
    name: "Science Diet Adult Chicken Recipe Cat Food",
    brand: "Hill's Science Diet",
    retailer: "Hill's Pet Nutrition",
    productUrl: "https://www.hillspet.com/cat-food/science-diet-adult-original-dry",
    species: "cat",
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness"],
    excludedIngredients: ["chicken", "grains"],
    avoidIngredientKeywords: ["chicken", "grain"],
    ingredientHighlights: ["Chicken"],
    lifeStage: "adult",
    tags: ["dry food", "adult", "cat", "nutrition"],
    currency: "USD",
    active: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt: "2026-07-13",
    sourceNote: "Official Hill's product page.",
    whyItFits:
      "A real adult cat food option for careful nutrition comparison in cat profiles.",
    whyCategoryFits:
      "Food products remain species-specific and are shown only when nutrition context supports comparison.",
    cautions:
      "Contains chicken and grains. Transition foods gradually and ask a veterinarian about medical diets or health concerns.",
  },
  {
    id: "earthbath-oatmeal-aloe-shampoo",
    name: "Oatmeal & Aloe Fragrance Free Pet Shampoo",
    brand: "Earthbath",
    retailer: "Earthbath",
    productUrl: "https://www.earthbath.com/products/oatmeal-aloe-shampoo-fragrance-free",
    species: "dog",
    category: "grooming",
    subcategory: "shampoo",
    recommendationKind: "product",
    protein: "Not applicable",
    concernTags: ["grooming", "itchy_skin", "sensitive_skin"],
    excludedIngredients: [],
    avoidIngredientKeywords: [],
    ingredientHighlights: ["Oatmeal", "Aloe"],
    lifeStage: "all",
    tags: ["grooming", "shampoo", "sensitive skin", "dog"],
    currency: "USD",
    active: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt: "2026-07-13",
    sourceNote: "Official Earthbath product page.",
    whyItFits:
      "A real grooming option for routine coat care when the profile context is not urgent or medical.",
    whyCategoryFits:
      "Grooming products can fit skin or coat context when Furvise is not treating symptoms as a diagnosis.",
    cautions:
      "Not a medical treatment. Stop use if irritation appears and contact a veterinarian for severe, painful, or worsening skin signs.",
  },
  {
    id: "greenies-original-regular-dog-dental-treats",
    name: "Original Regular Natural Dental Dog Treats",
    brand: "Greenies",
    retailer: "Greenies",
    productUrl: "https://www.greenies.com/products/dog/original-regular-dental-treats",
    species: "dog",
    category: "health_essentials",
    subcategory: "dental_treat",
    recommendationKind: "product",
    protein: "Poultry",
    concernTags: ["dental_care", "general_wellness"],
    excludedIngredients: ["chicken", "poultry"],
    avoidIngredientKeywords: ["chicken", "poultry", "gelatin", "wheat"],
    ingredientHighlights: ["Poultry", "Gelatin", "Wheat"],
    lifeStage: "adult",
    tags: ["dental", "dog", "treat", "poultry"],
    currency: "USD",
    active: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt: "2026-07-13",
    sourceNote: "Official Greenies product page.",
    whyItFits:
      "A real dog dental-care product for routine dental wellness context.",
    whyCategoryFits:
      "Dental care products are shown only for routine wellness support, not for urgent or painful mouth symptoms.",
    cautions:
      "Choose the correct size and supervise chewing. This is not dental treatment or a substitute for veterinary dental care.",
  },
  {
    id: "furminator-cat-deshedding-tool",
    name: "Undercoat deShedding Tool for Cats",
    brand: "FURminator",
    retailer: "FURminator",
    productUrl: "https://www.furminator.com/products/deshed/cat.aspx",
    species: "cat",
    category: "grooming",
    subcategory: "brush",
    recommendationKind: "product",
    protein: "Not applicable",
    concernTags: ["grooming", "general_wellness"],
    excludedIngredients: [],
    avoidIngredientKeywords: [],
    ingredientHighlights: [],
    lifeStage: "all",
    tags: ["grooming", "brush", "cat"],
    currency: "USD",
    active: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt: "2026-07-13",
    sourceNote: "Official FURminator cat deShedding product page.",
    whyItFits:
      "A real cat grooming option for shedding or routine coat-care context.",
    whyCategoryFits:
      "Grooming tools fit routine coat care when there are no severe skin or pain concerns.",
    cautions:
      "Use gently and avoid irritated, wounded, or painful skin. Ask a veterinarian about sudden hair loss or skin lesions.",
  },
];
