import type { MockProduct } from "../petwise";

const lastVerifiedAt = "2026-07-23";

const hillsDogChickenBarleyIngredients = [
  "Chicken",
  "Cracked Pearled Barley",
  "Brown Rice",
  "Brewers Rice",
  "Whole Grain Wheat",
  "Whole Grain Corn",
  "Corn Protein Meal",
  "Chicken Meal",
  "Chicken Fat",
  "Chicken Liver Flavor",
  "Soybean Meal",
  "Dried Beet Pulp",
  "Soybean Oil",
  "Lactic Acid",
  "Flaxseed",
  "Pork Liver Flavor",
  "Potassium Chloride",
  "Iodized Salt",
  "Whole Grain Oats",
  "Fructooligosaccharides (FOS)",
  "Choline Chloride",
  "Calcium Carbonate",
  "Vitamin E Supplement",
  "L-Ascorbyl-2-Polyphosphate (source of Vitamin C)",
  "Niacin Supplement",
  "Thiamine Mononitrate",
  "Vitamin A Supplement",
  "Calcium Pantothenate",
  "Biotin",
  "Vitamin B12 Supplement",
  "Riboflavin Supplement",
  "Pyridoxine Hydrochloride",
  "Folic Acid",
  "Vitamin D3 Supplement",
  "Taurine",
  "Ferrous Sulfate",
  "Zinc Oxide",
  "Copper Sulfate",
  "Manganous Oxide",
  "Calcium Iodate",
  "Sodium Selenite",
  "Mixed Tocopherols for freshness",
  "Natural Flavors",
  "Beta-Carotene",
];

const hillsCatChickenIngredients = [
  "Chicken",
  "Whole Grain Wheat",
  "Corn Protein Meal",
  "Whole Grain Corn",
  "Chicken Fat",
  "Chicken Meal",
  "Brewers Rice",
  "Dried Beet Pulp",
  "Soybean Meal",
  "Chicken Liver Flavor",
  "Soybean Oil",
  "Lactic Acid",
  "Fish Oil",
  "Calcium Sulfate",
  "Potassium Chloride",
  "L-Lysine",
  "Iodized Salt",
  "Choline Chloride",
  "Whole Grain Oats",
  "Fructooligosaccharides (FOS)",
  "Vitamin E Supplement",
  "L-Ascorbyl-2-Polyphosphate (source of Vitamin C)",
  "Thiamine Mononitrate",
  "Niacin Supplement",
  "Calcium Pantothenate",
  "Vitamin A Supplement",
  "Biotin",
  "Pyridoxine Hydrochloride",
  "Riboflavin Supplement",
  "Vitamin B12 Supplement",
  "Folic Acid",
  "Vitamin D3 Supplement",
  "Taurine",
  "Ferrous Sulfate",
  "Zinc Oxide",
  "Copper Sulfate",
  "Manganous Oxide",
  "Calcium Iodate",
  "Sodium Selenite",
  "Mixed Tocopherols for freshness",
  "Natural Flavors",
  "Beta-Carotene",
];

const purinaCatChowCompleteIngredients = [
  "Chicken By-Product Meal",
  "Ground Yellow Corn",
  "Corn Protein Meal",
  "Whole Grain Wheat",
  "Rice",
  "Soy Flour",
  "Beef Fat Preserved with Mixed-Tocopherols",
  "Chicken",
  "Fish Meal",
  "Liver Flavor",
  "Calcium Carbonate",
  "Phosphoric Acid",
  "Salt",
  "Potassium Chloride",
  "Choline Chloride",
  "Taurine",
  "Zinc Sulfate",
  "Ferrous Sulfate",
  "Manganese Sulfate",
  "Copper Sulfate",
  "Calcium Iodate",
  "Sodium Selenite",
  "Vitamin E Supplement",
  "Niacin",
  "Vitamin A Supplement",
  "Calcium Pantothenate",
  "Thiamine Mononitrate",
  "Riboflavin Supplement",
  "Vitamin B12 Supplement",
  "Pyridoxine Hydrochloride",
  "Folic Acid",
  "Vitamin D3 Supplement",
  "Biotin",
  "Menadione Sodium Bisulfite Complex",
  "DL-Methionine",
  "Red 40",
  "Yellow 5",
  "Blue 2",
];

const earthbathOatmealAloeIngredients = [
  "Purified water",
  "Renewable plant-derived and coconut-based cleansers",
  "Colloidal oatmeal",
  "Aloe vera",
  "Vitamins A, B, D, and E",
  "Panthenol",
  "Citric acid",
  "Phenoxyethanol",
];

const greeniesOriginalRegularIngredients = [
  "Wheat Flour",
  "Glycerin",
  "Wheat Gluten",
  "Gelatin",
  "Water",
  "Powdered Cellulose",
  "Lecithin",
  "Natural Poultry Flavor",
  "Dicalcium Phosphate",
  "Calcium Carbonate",
  "Potassium Chloride",
  "Choline Chloride",
  "Magnesium Amino Acid Chelate",
  "Zinc Amino Acid Chelate",
  "Iron Amino Acid Chelate",
  "Copper Amino Acid Chelate",
  "Manganese Amino Acid Chelate",
  "Sodium Selenite",
  "Potassium Iodide",
  "Fruit Juice Color",
  "Vitamin E Supplement",
  "Vitamin B12 Supplement",
  "D-Calcium Pantothenate (Vitamin B5)",
  "Niacin Supplement",
  "Riboflavin Supplement (Vitamin B2)",
  "Vitamin A Supplement",
  "Vitamin D3 Supplement",
  "Biotin",
  "Thiamine Mononitrate (Vitamin B1)",
  "Pyridoxine Hydrochloride (Vitamin B6)",
  "Folic Acid",
  "Turmeric Color",
];

const hillsFeedingDirections =
  "Adjust feeding amounts as needed to maintain ideal weight, transition gradually over 7 days, keep fresh water available, and review changing nutrition needs at checkups.";

const hillsFoodWarnings = [
  "Not recommended for puppies or pregnant or nursing dogs unless using an appropriate puppy formula.",
  "Keep the packaging out of reach of pets and children to prevent suffocation.",
];

const hillsCatFoodWarnings = [
  "Not recommended for kittens or pregnant or nursing cats unless using an appropriate kitten formula.",
  "Keep the packaging out of reach of pets and children to prevent suffocation.",
];

export const staticRealProducts: MockProduct[] = [
  {
    id: "hills-science-diet-adult-dog-chicken-barley",
    name: "Science Diet Adult Chicken & Barley Recipe Dog Food",
    brand: "Hill's Science Diet",
    retailer: "Hill's Pet Nutrition",
    productUrl: "https://www.hillspet.com/dog-food/science-diet-adult-original-dry",
    species: "dog",
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness", "picky_eating"],
    excludedIngredients: ["chicken", "grains"],
    avoidIngredientKeywords: ["chicken", "chicken meal", "chicken fat", "barley", "rice", "wheat", "corn", "soybean", "pork", "grain"],
    ingredientHighlights: ["Chicken", "Barley", "Rice", "Wheat", "Corn", "Soybean meal", "Pork liver flavor"],
    lifeStage: "adult",
    tags: ["dry food", "adult", "chicken", "nutrition"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.hillspet.com/dog-food/science-diet-adult-original-dry",
    verifiedProductPageUrl: "https://www.hillspet.com/dog-food/science-diet-adult-original-dry",
    verifiedDescription: "Adult dry dog food formulated for adult dogs 1 to 6 years old, with support for lean muscle and coat condition.",
    verifiedIngredients: hillsDogChickenBarleyIngredients,
    verifiedDirections: hillsFeedingDirections,
    verifiedWarnings: hillsFoodWarnings,
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Hill's product page.",
    whyItFits:
      "A real adult dog food option for nutrition comparisons when the profile supports looking at food.",
    whyCategoryFits:
      "Food is only shown when Furvise has a nutrition reason or the owner selected a nutrition goal.",
    cautions:
      "Contains chicken and grains. Transition foods gradually and ask a veterinarian about medical diets or health concerns.",
  },
  {
    id: "purina-cat-chow-complete-chicken",
    name: "Cat Chow Complete High Protein Dry Cat Food With Real Chicken",
    brand: "Purina Cat Chow",
    retailer: "Purina",
    productUrl: "https://www.purina.com/cats/shop/cat-chow-complete-dry-cat-food",
    species: "cat",
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness", "picky_eating"],
    excludedIngredients: ["chicken", "grains"],
    avoidIngredientKeywords: ["chicken", "chicken by-product meal", "corn", "wheat", "rice", "soy flour", "beef fat", "fish meal", "red 40", "yellow 5", "blue 2"],
    ingredientHighlights: ["Chicken by-product meal", "Ground yellow corn", "Whole grain wheat", "Rice", "Soy flour", "Fish meal"],
    lifeStage: "all",
    tags: ["dry food", "cat", "chicken", "nutrition"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.purina.com/cats/shop/cat-chow-complete-dry-cat-food",
    verifiedProductPageUrl: "https://www.purina.com/cats/shop/cat-chow-complete-dry-cat-food",
    verifiedDescription: "Dry cat food with real chicken, positioned for complete everyday nutrition for cats.",
    verifiedIngredients: purinaCatChowCompleteIngredients,
    verifiedDirections:
      "Use the feeding guide for portion ranges, adjust amounts to maintain ideal body condition, transition over 7 to 10 days, and provide fresh water daily.",
    verifiedWarnings: [
      "Feeding amounts are averages and should be adjusted for the cat's needs.",
      "See a veterinarian regularly for the pet's health.",
    ],
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Purina product page.",
    whyItFits:
      "A real cat food option for nutrition comparisons when the profile supports looking at food.",
    whyCategoryFits:
      "Cat food is shown only for cat profiles and only when nutrition context supports product comparison.",
    cautions:
      "Contains chicken by-product meal, corn, wheat, rice, soy flour, chicken, and fish meal. Transition foods gradually and check the label for current ingredients.",
  },
  {
    id: "hills-science-diet-adult-cat-chicken",
    name: "Science Diet Adult Chicken Recipe Cat Food",
    brand: "Hill's Science Diet",
    retailer: "Hill's Pet Nutrition",
    productUrl: "https://www.hillspet.com/cat-food/science-diet-adult-original-dry",
    species: "cat",
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness"],
    excludedIngredients: ["chicken", "grains", "fish"],
    avoidIngredientKeywords: ["chicken", "wheat", "corn", "rice", "soybean", "fish oil", "grain"],
    ingredientHighlights: ["Chicken", "Wheat", "Corn", "Rice", "Soybean meal", "Fish oil"],
    lifeStage: "adult",
    tags: ["dry food", "adult", "cat", "nutrition"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.hillspet.com/cat-food/science-diet-adult-original-dry",
    verifiedProductPageUrl: "https://www.hillspet.com/cat-food/science-diet-adult-original-dry",
    verifiedDescription: "Adult dry cat food formulated for adult cats 1 to 6 years old, with support for lean muscle and fur condition.",
    verifiedIngredients: hillsCatChickenIngredients,
    verifiedDirections: hillsFeedingDirections,
    verifiedWarnings: hillsCatFoodWarnings,
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Hill's product page.",
    whyItFits:
      "A real adult cat food option for careful nutrition comparison in cat profiles.",
    whyCategoryFits:
      "Food products remain species-specific and are shown only when nutrition context supports comparison.",
    cautions:
      "Contains chicken, grains, and fish oil. Transition foods gradually and ask a veterinarian about medical diets or health concerns.",
  },
  {
    id: "earthbath-oatmeal-aloe-shampoo",
    name: "Oatmeal & Aloe Fragrance Free Pet Shampoo",
    brand: "Earthbath",
    retailer: "Earthbath",
    productUrl: "https://www.earthbath.com/products/oatmeal-aloe-shampoo-fragrance-free",
    species: "dog",
    category: "grooming",
    subcategory: "shampoo",
    recommendationKind: "product",
    protein: "Not applicable",
    concernTags: ["grooming", "itchy_skin", "sensitive_skin"],
    excludedIngredients: [],
    avoidIngredientKeywords: ["coconut", "coconut-based cleansers", "oatmeal", "aloe", "panthenol", "citric acid", "phenoxyethanol"],
    ingredientHighlights: ["Colloidal oatmeal", "Aloe vera", "Coconut-based cleansers", "Panthenol"],
    lifeStage: "all",
    tags: ["grooming", "shampoo", "sensitive skin", "dog", "fragrance free", "oatmeal", "aloe"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.earthbath.com/products/oatmeal-aloe-shampoo-fragrance-free",
    verifiedProductPageUrl: "https://www.earthbath.com/products/oatmeal-aloe-shampoo-fragrance-free",
    verifiedDescription:
      "Fragrance-free, soap-free, pH-balanced dog shampoo for dry, itchy, sensitive skin and routine coat cleaning.",
    verifiedIngredients: earthbathOatmealAloeIngredients,
    verifiedDirections:
      "Shake well, lather thoroughly on a wet coat from head to tail while keeping out of eyes, leave on for at least 90 seconds, then rinse. It may be diluted ten parts water to one part shampoo, and diluted shampoo should be discarded after 24 hours.",
    verifiedWarnings: [
      "Use only on coat and skin.",
      "Flush thoroughly with clean water if eye contact occurs.",
      "Keep out of reach of children.",
      "If swallowed by a human, consult a physician.",
      "Stop use and contact a veterinarian if irritation develops.",
      "For pets with sensitivities, consult a veterinarian before using a new product.",
    ],
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Earthbath product page.",
    whyItFits:
      "A real grooming option for routine coat care when the profile context is not urgent or medical.",
    whyCategoryFits:
      "Grooming products can fit skin or coat context when Furvise is not treating symptoms as a diagnosis.",
    cautions:
      "Not a medical treatment. Stop use if irritation appears and contact a veterinarian for severe, painful, or worsening skin signs.",
  },
  {
    id: "greenies-original-regular-dog-dental-treats",
    name: "Original Regular Natural Dental Dog Treats",
    brand: "Greenies",
    retailer: "Greenies",
    productUrl: "https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-original",
    species: "dog",
    category: "health_essentials",
    subcategory: "dental_treat",
    recommendationKind: "product",
    protein: "Poultry",
    concernTags: ["dental_care", "general_wellness"],
    excludedIngredients: ["chicken", "poultry", "grains"],
    avoidIngredientKeywords: ["wheat", "wheat gluten", "gelatin", "poultry", "chicken", "dicalcium phosphate", "fruit juice color", "turmeric"],
    ingredientHighlights: ["Wheat flour", "Wheat gluten", "Gelatin", "Natural poultry flavor"],
    lifeStage: "adult",
    tags: ["dental", "dog", "treat", "poultry", "wheat"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-original",
    verifiedProductPageUrl: "https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-original",
    verifiedDescription:
      "Regular-size adult dog dental treat for dogs 25 to 50 lb, positioned for plaque, tartar, gum, and breath support.",
    verifiedIngredients: greeniesOriginalRegularIngredients,
    verifiedDirections:
      "Feed one dental treat per day for dogs 25 to 50 lb, provide fresh drinking water, and reduce the dog's main meal by the treat calories listed on the package.",
    verifiedWarnings: [
      "Not suitable for dogs less than 5 lb or dogs less than 6 months of age.",
      "Monitor the dog to make sure the treat is adequately chewed.",
      "Gulping an edible item can be harmful or even fatal to a dog.",
      "Choose the correct treat size for the dog's weight.",
    ],
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Greenies product page.",
    whyItFits:
      "A real dog dental-care product for routine dental wellness context.",
    whyCategoryFits:
      "Dental care products are shown only for routine wellness support, not for urgent or painful mouth symptoms.",
    cautions:
      "Choose the correct size and supervise chewing. This is not dental treatment or a substitute for veterinary dental care.",
  },
  {
    id: "furminator-cat-deshedding-tool",
    name: "Undercoat deShedding Tool for Cats",
    brand: "FURminator",
    retailer: "FURminator",
    productUrl: "https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-small-cat-short-hair",
    species: "cat",
    category: "grooming",
    subcategory: "brush",
    recommendationKind: "product",
    protein: "Not applicable",
    concernTags: ["grooming", "general_wellness"],
    excludedIngredients: [],
    avoidIngredientKeywords: [],
    ingredientHighlights: [],
    lifeStage: "all",
    tags: ["grooming", "brush", "cat", "deshedding"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-small-cat-short-hair",
    verifiedProductPageUrl: "https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-small-cat-short-hair",
    verifiedDescription:
      "Cat undercoat deShedding tool with a stainless steel edge, curved skin guard, ergonomic handle, and hair-release button.",
    verifiedDirections:
      "Use on a completely dry coat, inspect the pet first, remove tangles or mats before deShedding, then gently stroke in the direction of hair growth with extra care near sensitive body areas.",
    verifiedWarnings: [
      "Use only as directed.",
      "Do not use on pets with sores, bruises, or skin conditions before seeking veterinary treatment.",
      "Avoid excessive pressure or repeated strokes in one area.",
      "Discontinue use if redness or irritation appears.",
      "The tool should not be used on non-shedding breeds or pets with particularly sensitive skin.",
    ],
    enrichmentStatus: "partial",
    verificationSource: "brand_page",
    ingredientsVerified: false,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official FURminator cat deShedding product page.",
    whyItFits:
      "A real cat grooming option for shedding or routine coat-care context.",
    whyCategoryFits:
      "Grooming tools fit routine coat care when there are no severe skin or pain concerns.",
    cautions:
      "Use gently and avoid irritated, wounded, or painful skin. Ask a veterinarian about sudden hair loss or skin lesions.",
  },
];

