import type { MockProduct } from "../petwise";

const lastVerifiedAt = "2026-07-23";

const hillsDogChickenBarleyIngredients = [
  "Chicken",
  "Cracked Pearled Barley",
  "Brown Rice",
  "Brewers Rice",
  "Whole Grain Wheat",
  "Whole Grain Corn",
  "Corn Protein Meal",
  "Chicken Meal",
  "Chicken Fat",
  "Chicken Liver Flavor",
  "Soybean Meal",
  "Dried Beet Pulp",
  "Soybean Oil",
  "Lactic Acid",
  "Flaxseed",
  "Pork Liver Flavor",
  "Potassium Chloride",
  "Iodized Salt",
  "Whole Grain Oats",
  "Fructooligosaccharides (FOS)",
  "Choline Chloride",
  "Calcium Carbonate",
  "Vitamin E Supplement",
  "L-Ascorbyl-2-Polyphosphate (source of Vitamin C)",
  "Niacin Supplement",
  "Thiamine Mononitrate",
  "Vitamin A Supplement",
  "Calcium Pantothenate",
  "Biotin",
  "Vitamin B12 Supplement",
  "Riboflavin Supplement",
  "Pyridoxine Hydrochloride",
  "Folic Acid",
  "Vitamin D3 Supplement",
  "Taurine",
  "Ferrous Sulfate",
  "Zinc Oxide",
  "Copper Sulfate",
  "Manganous Oxide",
  "Calcium Iodate",
  "Sodium Selenite",
  "Mixed Tocopherols for freshness",
  "Natural Flavors",
  "Beta-Carotene",
];

const hillsCatChickenIngredients = [
  "Chicken",
  "Whole Grain Wheat",
  "Corn Protein Meal",
  "Whole Grain Corn",
  "Chicken Fat",
  "Chicken Meal",
  "Brewers Rice",
  "Dried Beet Pulp",
  "Soybean Meal",
  "Chicken Liver Flavor",
  "Soybean Oil",
  "Lactic Acid",
  "Fish Oil",
  "Calcium Sulfate",
  "Potassium Chloride",
  "L-Lysine",
  "Iodized Salt",
  "Choline Chloride",
  "Whole Grain Oats",
  "Fructooligosaccharides (FOS)",
  "Vitamin E Supplement",
  "L-Ascorbyl-2-Polyphosphate (source of Vitamin C)",
  "Thiamine Mononitrate",
  "Niacin Supplement",
  "Calcium Pantothenate",
  "Vitamin A Supplement",
  "Biotin",
  "Pyridoxine Hydrochloride",
  "Riboflavin Supplement",
  "Vitamin B12 Supplement",
  "Folic Acid",
  "Vitamin D3 Supplement",
  "Taurine",
  "Ferrous Sulfate",
  "Zinc Oxide",
  "Copper Sulfate",
  "Manganous Oxide",
  "Calcium Iodate",
  "Sodium Selenite",
  "Mixed Tocopherols for freshness",
  "Natural Flavors",
  "Beta-Carotene",
];

const purinaCatChowCompleteIngredients = [
  "Chicken By-Product Meal",
  "Ground Yellow Corn",
  "Corn Protein Meal",
  "Whole Grain Wheat",
  "Rice",
  "Soy Flour",
  "Beef Fat Preserved with Mixed-Tocopherols",
  "Chicken",
  "Fish Meal",
  "Liver Flavor",
  "Calcium Carbonate",
  "Phosphoric Acid",
  "Salt",
  "Potassium Chloride",
  "Choline Chloride",
  "Taurine",
  "Zinc Sulfate",
  "Ferrous Sulfate",
  "Manganese Sulfate",
  "Copper Sulfate",
  "Calcium Iodate",
  "Sodium Selenite",
  "Vitamin E Supplement",
  "Niacin",
  "Vitamin A Supplement",
  "Calcium Pantothenate",
  "Thiamine Mononitrate",
  "Riboflavin Supplement",
  "Vitamin B12 Supplement",
  "Pyridoxine Hydrochloride",
  "Folic Acid",
  "Vitamin D3 Supplement",
  "Biotin",
  "Menadione Sodium Bisulfite Complex",
  "DL-Methionine",
  "Red 40",
  "Yellow 5",
  "Blue 2",
];

const earthbathOatmealAloeIngredients = [
  "Purified water",
  "Renewable plant-derived and coconut-based cleansers",
  "Colloidal oatmeal",
  "Aloe vera",
  "Vitamins A, B, D, and E",
  "Panthenol",
  "Citric acid",
  "Phenoxyethanol",
];

const greeniesOriginalRegularIngredients = [
  // Original size variants use the same verified formula.
  "Wheat Flour",
  "Glycerin",
  "Wheat Gluten",
  "Gelatin",
  "Water",
  "Powdered Cellulose",
  "Lecithin",
  "Natural Poultry Flavor",
  "Dicalcium Phosphate",
  "Calcium Carbonate",
  "Potassium Chloride",
  "Choline Chloride",
  "Magnesium Amino Acid Chelate",
  "Zinc Amino Acid Chelate",
  "Iron Amino Acid Chelate",
  "Copper Amino Acid Chelate",
  "Manganese Amino Acid Chelate",
  "Sodium Selenite",
  "Potassium Iodide",
  "Fruit Juice Color",
  "Vitamin E Supplement",
  "Vitamin B12 Supplement",
  "D-Calcium Pantothenate (Vitamin B5)",
  "Niacin Supplement",
  "Riboflavin Supplement (Vitamin B2)",
  "Vitamin A Supplement",
  "Vitamin D3 Supplement",
  "Biotin",
  "Thiamine Mononitrate (Vitamin B1)",
  "Pyridoxine Hydrochloride (Vitamin B6)",
  "Folic Acid",
  "Turmeric Color",
];

const earthbathHypoallergenicIngredients = [
  'Purified water',
  'Renewable plant-derived and coconut-based cleansers',
  'Aloe vera',
  'Vitamins A, B, D, and E',
  'Panthenol',
  'Citric acid',
  'Phenoxyethanol',
];

const earthbathHypoallergenicWipesIngredients = [
  'Deionized water',
  'Sodium cocoyl hydrolyzed soy protein',
  'Oryza sativa (rice) extract',
  'Tocopheryl acetate (vitamin E)',
  'Persea gratissima (avocado) oil',
  'Potassium sorbate',
  'Chamomilla recutita (matricaria) flower extract',
  'Aloe barbadensis leaf juice (aloe vera)',
  'Hedychium coronarium (awapuhi) root extract',
  'Helianthus annuus (sunflower) seed oil',
  'Panax ginseng root extract',
  'Citric acid',
  'Phenoxyethanol',
];

const earthbathGreenTeaWipesIngredients = [
  ...earthbathHypoallergenicWipesIngredients.slice(0, 11),
  'Botanical fragrance of green tea leaf',
  'Citric acid',
  'Phenoxyethanol',
];

const earthbathOatmealWipesIngredients = [
  ...earthbathHypoallergenicWipesIngredients.slice(0, 11),
  'Hydrolyzed oat protein',
  'Avena sativa (oat) kernel extract',
  'Botanical fragrance of vanilla almond',
  'Citric acid',
  'Phenoxyethanol',
];

const purinaProPlanSensitiveDryIngredients = [
  'Salmon', 'Rice', 'Barley', 'Canola meal', 'Oat meal', 'Fish meal', 'Salmon meal',
  'Beef fat preserved with mixed-tocopherols', 'Dried yeast', 'Natural flavor', 'Sunflower oil',
  'Fish oil', 'Dried chicory root', 'Calcium carbonate', 'Salt', 'Potassium chloride',
  'L-Lysine monohydrochloride', 'Vitamin E supplement', 'Niacin (Vitamin B-3)',
  'Vitamin A supplement', 'Calcium pantothenate (Vitamin B-5)', 'Thiamine mononitrate (Vitamin B-1)',
  'Vitamin B-12 supplement', 'Riboflavin supplement (Vitamin B-2)', 'Pyridoxine hydrochloride',
  'Folic acid (Vitamin B-9)', 'Menadione sodium bisulfite complex (Vitamin K)', 'Biotin (Vitamin B-7)',
  'Vitamin D-3 supplement', 'Taurine', 'Zinc sulfate', 'Ferrous sulfate', 'Manganese sulfate',
  'Copper sulfate', 'Calcium iodate', 'Sodium selenite', 'DL-Methionine', 'Choline chloride',
  'L-ascorbyl-2-polyphosphate (Vitamin C)',
];

const purinaProPlanSensitiveWetIngredients = [
  'Water', 'Fish', 'Liver', 'Salmon', 'Rice', 'Potato protein', 'Oat meal', 'Corn oil',
  'Potassium chloride', 'Magnesium sulfate', 'Zinc sulfate', 'Ferrous sulfate', 'Copper sulfate',
  'Manganese sulfate', 'Potassium iodide', 'Sodium selenite', 'Inulin', 'Carrageenan',
  'Locust bean gum', 'Tricalcium phosphate', 'Xanthan gum', 'Guar gum', 'Choline chloride',
  'Vitamin E supplement', 'Thiamine mononitrate (Vitamin B-1)', 'Niacin (Vitamin B-3)',
  'Calcium pantothenate (Vitamin B-5)', 'Vitamin A supplement',
  'Menadione sodium bisulfite complex (Vitamin K)', 'Pyridoxine hydrochloride (Vitamin B-6)',
  'Riboflavin supplement (Vitamin B-2)', 'Vitamin B-12 supplement', 'Biotin (Vitamin B-7)',
  'Folic acid (Vitamin B-9)', 'Vitamin D-3 supplement',
];

const greeniesFreshRegularIngredients = [
  'Wheat Flour', 'Glycerin', 'Wheat Gluten', 'Gelatin', 'Water', 'Powdered Cellulose', 'Lecithin',
  'Natural Flavor', 'Dicalcium Phosphate', 'Dried Spearmint', 'Calcium Carbonate', 'Potassium Chloride',
  'Choline Chloride', 'Magnesium Amino Acid Chelate', 'Zinc Amino Acid Chelate',
  'Iron Amino Acid Chelate', 'Copper Amino Acid Chelate', 'Manganese Amino Acid Chelate',
  'Sodium Selenite', 'Potassium Iodide', 'Fruit Juice Color', 'Natural Peppermint Flavor',
  'DL-Alpha Tocopherol Acetate (source of Vitamin E)', 'Vitamin B12 Supplement',
  'D-Calcium Pantothenate (Vitamin B5)', 'Niacin Supplement', 'Riboflavin Supplement (Vitamin B2)',
  'Vitamin A Supplement', 'Vitamin D3 Supplement', 'Biotin', 'Thiamine Mononitrate (Vitamin B1)',
  'Pyridoxine Hydrochloride (Vitamin B6)', 'Folic Acid', 'Turmeric Color',
];

const hillsFeedingDirections =
  "Adjust feeding amounts as needed to maintain ideal weight, transition gradually over 7 days, keep fresh water available, and review changing nutrition needs at checkups.";

const hillsFoodWarnings = [
  "Not recommended for puppies or pregnant or nursing dogs unless using an appropriate puppy formula.",
  "Keep the packaging out of reach of pets and children to prevent suffocation.",
];

const hillsCatFoodWarnings = [
  "Not recommended for kittens or pregnant or nursing cats unless using an appropriate kitten formula.",
  "Keep the packaging out of reach of pets and children to prevent suffocation.",
];

export const staticRealProducts: MockProduct[] = [
  {
    id: "hills-science-diet-adult-dog-chicken-barley",
    name: "Science Diet Adult Chicken & Barley Recipe Dog Food",
    brand: "Hill's Science Diet",
    shortDescription: "Adult dry dog food with chicken and barley for routine feeding.",
    productTypeLabel: "Adult dry dog food",
    retailer: "Hill's Pet Nutrition",
    productUrl: "https://www.hillspet.com/dog-food/science-diet-adult-original-dry",
    species: ["dog"],
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness", "picky_eating"],
    excludedIngredients: ["chicken", "grains"],
    avoidIngredientKeywords: ["chicken", "chicken meal", "chicken fat", "barley", "rice", "wheat", "corn", "soybean", "pork", "grain"],
    ingredientHighlights: ["Chicken", "Barley", "Rice", "Wheat", "Corn", "Soybean meal", "Pork liver flavor"],
    lifeStage: "adult",
    tags: ["dry food", "adult", "chicken", "nutrition"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.hillspet.com/dog-food/science-diet-adult-original-dry",
    verifiedProductPageUrl: "https://www.hillspet.com/dog-food/science-diet-adult-original-dry",
    verifiedDescription: "Adult dry dog food formulated for adult dogs 1 to 6 years old, with support for lean muscle and coat condition.",
    verifiedIngredients: hillsDogChickenBarleyIngredients,
    verifiedDirections: hillsFeedingDirections,
    verifiedWarnings: hillsFoodWarnings,
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Hill's product page.",
    whyItFits:
      "A real adult dog food option for nutrition comparisons when the profile supports looking at food.",
    whyCategoryFits:
      "Food is only shown when Furvise has a nutrition reason or the owner selected a nutrition goal.",
    cautions:
      "Contains chicken and grains. Transition foods gradually and ask a veterinarian about medical diets or health concerns.",
  },
  {
    id: "purina-cat-chow-complete-chicken",
    name: "Cat Chow Complete High Protein Dry Cat Food With Real Chicken",
    brand: "Purina Cat Chow",
    shortDescription: "Dry cat food with chicken for complete everyday nutrition.",
    productTypeLabel: "Dry cat food",
    retailer: "Purina",
    productUrl: "https://www.purina.com/cats/shop/cat-chow-complete-dry-cat-food",
    species: ["cat"],
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness", "picky_eating"],
    excludedIngredients: ["chicken", "grains"],
    avoidIngredientKeywords: ["chicken", "chicken by-product meal", "corn", "wheat", "rice", "soy flour", "beef fat", "fish meal", "red 40", "yellow 5", "blue 2"],
    ingredientHighlights: ["Chicken by-product meal", "Ground yellow corn", "Whole grain wheat", "Rice", "Soy flour", "Fish meal"],
    lifeStage: "all",
    tags: ["dry food", "cat", "chicken", "nutrition"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.purina.com/cats/shop/cat-chow-complete-dry-cat-food",
    verifiedProductPageUrl: "https://www.purina.com/cats/shop/cat-chow-complete-dry-cat-food",
    verifiedDescription: "Dry cat food with real chicken, positioned for complete everyday nutrition for cats.",
    verifiedIngredients: purinaCatChowCompleteIngredients,
    verifiedDirections:
      "Use the feeding guide for portion ranges, adjust amounts to maintain ideal body condition, transition over 7 to 10 days, and provide fresh water daily.",
    verifiedWarnings: [
      "Feeding amounts are averages and should be adjusted for the cat's needs.",
      "See a veterinarian regularly for the pet's health.",
    ],
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Purina product page.",
    whyItFits:
      "A real cat food option for nutrition comparisons when the profile supports looking at food.",
    whyCategoryFits:
      "Cat food is shown only for cat profiles and only when nutrition context supports product comparison.",
    cautions:
      "Contains chicken by-product meal, corn, wheat, rice, soy flour, chicken, and fish meal. Transition foods gradually and check the label for current ingredients.",
  },
  {
    id: "hills-science-diet-adult-cat-chicken",
    name: "Science Diet Adult Chicken Recipe Cat Food",
    brand: "Hill's Science Diet",
    shortDescription: "Adult dry cat food with chicken for routine feeding.",
    productTypeLabel: "Adult dry cat food",
    retailer: "Hill's Pet Nutrition",
    productUrl: "https://www.hillspet.com/cat-food/science-diet-adult-original-dry",
    species: ["cat"],
    category: "food",
    subcategory: "dry_food",
    recommendationKind: "product",
    protein: "Chicken",
    concernTags: ["general_wellness"],
    excludedIngredients: ["chicken", "grains", "fish"],
    avoidIngredientKeywords: ["chicken", "wheat", "corn", "rice", "soybean", "fish oil", "grain"],
    ingredientHighlights: ["Chicken", "Wheat", "Corn", "Rice", "Soybean meal", "Fish oil"],
    lifeStage: "adult",
    tags: ["dry food", "adult", "cat", "nutrition"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.hillspet.com/cat-food/science-diet-adult-original-dry",
    verifiedProductPageUrl: "https://www.hillspet.com/cat-food/science-diet-adult-original-dry",
    verifiedDescription: "Adult dry cat food formulated for adult cats 1 to 6 years old, with support for lean muscle and fur condition.",
    verifiedIngredients: hillsCatChickenIngredients,
    verifiedDirections: hillsFeedingDirections,
    verifiedWarnings: hillsCatFoodWarnings,
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Hill's product page.",
    whyItFits:
      "A real adult cat food option for careful nutrition comparison in cat profiles.",
    whyCategoryFits:
      "Food products remain species-specific and are shown only when nutrition context supports comparison.",
    cautions:
      "Contains chicken, grains, and fish oil. Transition foods gradually and ask a veterinarian about medical diets or health concerns.",
  },
  {
    id: "earthbath-oatmeal-aloe-shampoo",
    name: "Oatmeal & Aloe Fragrance Free Pet Shampoo",
    brand: "Earthbath",
    shortDescription: "Fragrance-free dog shampoo for dry, itchy, sensitive skin.",
    productTypeLabel: "Dog grooming shampoo",
    retailer: "Earthbath",
    productUrl: "https://www.earthbath.com/products/oatmeal-aloe-shampoo-fragrance-free",
    species: ["dog"],
    category: "grooming",
    subcategory: "shampoo",
    recommendationKind: "product",
    protein: "Not applicable",
    concernTags: ["grooming", "itchy_skin", "sensitive_skin"],
    excludedIngredients: [],
    avoidIngredientKeywords: ["coconut", "coconut-based cleansers", "oatmeal", "aloe", "panthenol", "citric acid", "phenoxyethanol"],
    ingredientHighlights: ["Colloidal oatmeal", "Aloe vera", "Coconut-based cleansers", "Panthenol"],
    lifeStage: "all",
    tags: ["grooming", "shampoo", "sensitive skin", "dog", "fragrance free", "oatmeal", "aloe"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.earthbath.com/products/oatmeal-aloe-shampoo-fragrance-free",
    verifiedProductPageUrl: "https://www.earthbath.com/products/oatmeal-aloe-shampoo-fragrance-free",
    verifiedDescription:
      "Fragrance-free, soap-free, pH-balanced dog shampoo for dry, itchy, sensitive skin and routine coat cleaning.",
    verifiedIngredients: earthbathOatmealAloeIngredients,
    verifiedDirections:
      "Shake well, lather thoroughly on a wet coat from head to tail while keeping out of eyes, leave on for at least 90 seconds, then rinse. It may be diluted ten parts water to one part shampoo, and diluted shampoo should be discarded after 24 hours.",
    verifiedWarnings: [
      "Use only on coat and skin.",
      "Flush thoroughly with clean water if eye contact occurs.",
      "Keep out of reach of children.",
      "If swallowed by a human, consult a physician.",
      "Stop use and contact a veterinarian if irritation develops.",
      "For pets with sensitivities, consult a veterinarian before using a new product.",
    ],
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Earthbath product page.",
    whyItFits:
      "A real grooming option for routine coat care when the profile context is not urgent or medical.",
    whyCategoryFits:
      "Grooming products can fit skin or coat context when Furvise is not treating symptoms as a diagnosis.",
    cautions:
      "Not a medical treatment. Stop use if irritation appears and contact a veterinarian for severe, painful, or worsening skin signs.",
  },
  {
    id: "greenies-original-regular-dog-dental-treats",
    name: "Original Regular Natural Dental Dog Treats",
    brand: "Greenies",
    shortDescription: "Daily dental chews sized for adult dogs weighing 25 to 50 lb.",
    productTypeLabel: "Dog dental treats",
    retailer: "Greenies",
    productUrl: "https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-original",
    species: ["dog"],
    category: "health_essentials",
    subcategory: "dental_treat",
    recommendationKind: "product",
    protein: "Poultry",
    concernTags: ["dental_care", "general_wellness"],
    excludedIngredients: ["chicken", "poultry", "grains"],
    avoidIngredientKeywords: ["wheat", "wheat gluten", "gelatin", "poultry", "chicken", "dicalcium phosphate", "fruit juice color", "turmeric"],
    ingredientHighlights: ["Wheat flour", "Wheat gluten", "Gelatin", "Natural poultry flavor"],
    lifeStage: "adult",
    tags: ["dental", "dog", "treat", "poultry", "wheat"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-original",
    verifiedProductPageUrl: "https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-original",
    verifiedDescription:
      "Regular-size adult dog dental treat for dogs 25 to 50 lb, positioned for plaque, tartar, gum, and breath support.",
    verifiedIngredients: greeniesOriginalRegularIngredients,
    verifiedDirections:
      "Feed one dental treat per day for dogs 25 to 50 lb, provide fresh drinking water, and reduce the dog's main meal by the treat calories listed on the package.",
    verifiedWarnings: [
      "Not suitable for dogs less than 5 lb or dogs less than 6 months of age.",
      "Monitor the dog to make sure the treat is adequately chewed.",
      "Gulping an edible item can be harmful or even fatal to a dog.",
      "Choose the correct treat size for the dog's weight.",
    ],
    enrichmentStatus: "verified",
    verificationSource: "brand_page",
    ingredientsVerified: true,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official Greenies product page.",
    whyItFits:
      "A real dog dental-care product for routine dental wellness context.",
    whyCategoryFits:
      "Dental care products are shown only for routine wellness support, not for urgent or painful mouth symptoms.",
    cautions:
      "Choose the correct size and supervise chewing. This is not dental treatment or a substitute for veterinary dental care.",
  },
  {
    id: "furminator-cat-deshedding-tool",
    name: "Undercoat deShedding Tool for Cats",
    brand: "FURminator",
    shortDescription: "Undercoat deShedding tool for short-haired cats.",
    productTypeLabel: "Cat grooming tool",
    retailer: "FURminator",
    productUrl: "https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-small-cat-short-hair",
    species: ["cat"],
    category: "grooming",
    subcategory: "brush",
    recommendationKind: "product",
    protein: "Not applicable",
    concernTags: ["grooming", "general_wellness"],
    excludedIngredients: [],
    avoidIngredientKeywords: [],
    ingredientHighlights: [],
    lifeStage: "all",
    tags: ["grooming", "brush", "cat", "deshedding"],
    currency: "USD",
    active: true,
    source: "curated",
    sourceUrl: "https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-small-cat-short-hair",
    verifiedProductPageUrl: "https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-small-cat-short-hair",
    verifiedDescription:
      "Cat undercoat deShedding tool with a stainless steel edge, curved skin guard, ergonomic handle, and hair-release button.",
    verifiedDirections:
      "Use on a completely dry coat, inspect the pet first, remove tangles or mats before deShedding, then gently stroke in the direction of hair growth with extra care near sensitive body areas.",
    verifiedWarnings: [
      "Use only as directed.",
      "Do not use on pets with sores, bruises, or skin conditions before seeking veterinary treatment.",
      "Avoid excessive pressure or repeated strokes in one area.",
      "Discontinue use if redness or irritation appears.",
      "The tool should not be used on non-shedding breeds or pets with particularly sensitive skin.",
    ],
    enrichmentStatus: "partial",
    verificationSource: "brand_page",
    ingredientsVerified: false,
    availableCountries: ["US"],
    evidenceType: "curated_static",
    lastVerifiedAt,
    sourceNote: "Official FURminator cat deShedding product page.",
    whyItFits:
      "A real cat grooming option for shedding or routine coat-care context.",
    whyCategoryFits:
      "Grooming tools fit routine coat care when there are no severe skin or pain concerns.",
    cautions:
      "Use gently and avoid irritated, wounded, or painful skin. Ask a veterinarian about sudden hair loss or skin lesions.",
  },
  {
    id: 'earthbath-hypoallergenic-shampoo',
    brand: 'Earthbath',
    name: 'Hypoallergenic Shampoo',
    category: 'grooming',
    subcategory: 'shampoo',
    species: ['dog'],
    shortDescription: 'Fragrance-free shampoo for dogs with sensitive skin.',
    productTypeLabel: 'Dog grooming shampoo',
    retailer: 'Earthbath',
    productUrl: 'https://earthbath.com/products/hypoallergenic-shampoo',
    recommendationKind: 'product',
    protein: 'Not applicable',
    concernTags: ['grooming', 'sensitive_skin', 'itchy_skin'],
    excludedIngredients: [],
    avoidIngredientKeywords: ['coconut', 'aloe', 'panthenol', 'citric acid', 'phenoxyethanol'],
    ingredientHighlights: ['Coconut-based cleansers', 'Aloe vera', 'Panthenol'],
    lifeStage: 'all',
    tags: ['grooming', 'shampoo', 'dog', 'sensitive skin', 'fragrance free'],
    currency: 'USD',
    active: true,
    source: 'curated',
    sourceUrl: 'https://earthbath.com/products/hypoallergenic-shampoo',
    verifiedProductPageUrl: 'https://earthbath.com/products/hypoallergenic-shampoo',
    verifiedDescription: 'Mild fragrance-free shampoo for dogs with skin sensitivities; intended for pets over 6 weeks old.',
    verifiedIngredients: earthbathHypoallergenicIngredients,
    verifiedDirections: 'Shake well, lather on a wet coat from head to tail while avoiding the eyes, leave on for at least 90 seconds, then rinse. Diluted shampoo should be discarded after 24 hours.',
    verifiedWarnings: ['Use only on coat and skin.', 'Flush with clean water if eye contact occurs.', 'Stop use and contact a veterinarian if irritation develops.'],
    ingredientsVerified: true,
    enrichmentStatus: 'verified',
    verificationSource: 'brand_page',
    availableCountries: ['US'],
    evidenceType: 'curated_static',
    lastVerifiedAt,
    sourceNote: 'Official Earthbath product page.',
    whyItFits: 'A real fragrance-free shampoo for routine dog grooming.',
    whyCategoryFits: 'Shampoo fits routine coat cleaning when symptoms do not need urgent care.',
    cautions: 'Stop use if irritation appears and contact a veterinarian about persistent skin concerns.',
  },
  {
    id: 'earthbath-hypoallergenic-grooming-wipes',
    brand: 'Earthbath',
    name: 'Hypoallergenic Grooming Wipes',
    category: 'grooming',
    subcategory: 'wipes',
    species: ['dog'],
    shortDescription: 'Fragrance-free wipes for cleaning paws, coat, and undercoat between baths.',
    productTypeLabel: 'Dog grooming wipes',
    retailer: 'Earthbath',
    productUrl: 'https://www.earthbath.com/products/hypoallergenic-dog-wipes',
    recommendationKind: 'product',
    protein: 'Not applicable',
    concernTags: ['grooming', 'paw_care', 'sensitive_skin'],
    excludedIngredients: [],
    avoidIngredientKeywords: ['soy', 'rice', 'avocado', 'aloe', 'sunflower', 'citric acid', 'phenoxyethanol'],
    ingredientHighlights: ['Aloe vera', 'Avocado oil', 'Vitamin E'],
    lifeStage: 'all',
    tags: ['grooming', 'wipes', 'dog', 'paw wipes', 'fragrance free'],
    currency: 'USD',
    active: true,
    source: 'curated',
    sourceUrl: 'https://www.earthbath.com/products/hypoallergenic-dog-wipes',
    verifiedProductPageUrl: 'https://www.earthbath.com/products/hypoallergenic-dog-wipes',
    verifiedDescription: 'Fragrance-free grooming wipes for removing dirt and odor from paws, coat, and undercoat between baths.',
    verifiedIngredients: earthbathHypoallergenicWipesIngredients,
    verifiedDirections: 'Remove one wipe, wipe the pet, close the lid tightly, store in a cool dry place, and do not flush the wipe.',
    verifiedWarnings: ['Avoid eye contact.', 'Flush with water if eye contact occurs.', 'Stop use and contact a veterinarian if irritation develops.'],
    ingredientsVerified: true,
    enrichmentStatus: 'verified',
    verificationSource: 'brand_page',
    availableCountries: ['US'],
    evidenceType: 'curated_static',
    lastVerifiedAt,
    sourceNote: 'Official Earthbath product page.',
    whyItFits: 'A real wipe option for routine paw and coat cleaning between baths.',
    whyCategoryFits: 'Grooming wipes fit routine surface cleaning and coat care.',
    cautions: 'Avoid the eyes and stop use if irritation appears.',
  },
  {
    id: 'earthbath-green-tea-awapuhi-grooming-wipes', brand: 'Earthbath',
    name: 'Green Tea & Awapuhi Grooming Wipes', category: 'grooming', subcategory: 'wipes', species: ['dog'],
    shortDescription: 'Plant-based wipes for cleaning dirty paws and coats between baths.',
    productTypeLabel: 'Dog grooming wipes', retailer: 'Earthbath',
    productUrl: 'https://www.earthbath.com/products/grooming-wipes-green-tea-awapuhi', recommendationKind: 'product',
    protein: 'Not applicable', concernTags: ['grooming', 'paw_care'], excludedIngredients: [],
    avoidIngredientKeywords: ['soy', 'rice', 'avocado', 'aloe', 'sunflower', 'fragrance', 'citric acid', 'phenoxyethanol'],
    ingredientHighlights: ['Green tea fragrance', 'Aloe vera', 'Avocado oil', 'Vitamin E'],
    lifeStage: 'all', tags: ['grooming', 'wipes', 'dog', 'paw wipes', 'coat cleaning'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.earthbath.com/products/grooming-wipes-green-tea-awapuhi',
    verifiedProductPageUrl: 'https://www.earthbath.com/products/grooming-wipes-green-tea-awapuhi',
    verifiedDescription: 'Plant-based grooming wipes for removing dirt and odors from paws, undercoat, and coat between baths.',
    verifiedIngredients: earthbathGreenTeaWipesIngredients,
    verifiedDirections: 'Remove one wipe, wipe the pet, close the lid tightly, store in a cool dry place, and do not flush the wipe.',
    verifiedWarnings: ['Avoid eye contact.', 'Flush with water if eye contact occurs.', 'Stop use and contact a veterinarian if irritation develops.'],
    ingredientsVerified: true, enrichmentStatus: 'verified', verificationSource: 'brand_page',
    availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt,
    sourceNote: 'Official Earthbath product page.', whyItFits: 'A real wipe option for routine paw and coat cleaning.',
    whyCategoryFits: 'Grooming wipes fit routine surface cleaning between baths.', cautions: 'Avoid the eyes and stop use if irritation appears.',
  },
  {
    id: 'earthbath-oatmeal-aloe-grooming-wipes', brand: 'Earthbath',
    name: 'Oatmeal & Aloe Grooming Wipes', category: 'grooming', subcategory: 'wipes', species: ['dog'],
    shortDescription: 'Oatmeal and aloe wipes for cleaning a dog between baths.',
    productTypeLabel: 'Dog grooming wipes', retailer: 'Earthbath',
    productUrl: 'https://earthbath.com/products/oatmeal-aloe-grooming-wipes-1', recommendationKind: 'product',
    protein: 'Not applicable', concernTags: ['grooming', 'paw_care', 'sensitive_skin', 'itchy_skin'], excludedIngredients: [],
    avoidIngredientKeywords: ['soy', 'rice', 'avocado', 'aloe', 'sunflower', 'oat', 'oatmeal', 'fragrance', 'citric acid', 'phenoxyethanol'],
    ingredientHighlights: ['Oat protein', 'Oat kernel extract', 'Aloe vera', 'Avocado oil'],
    lifeStage: 'all', tags: ['grooming', 'wipes', 'dog', 'paw wipes', 'oatmeal', 'aloe'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://earthbath.com/products/oatmeal-aloe-grooming-wipes-1',
    verifiedProductPageUrl: 'https://earthbath.com/products/oatmeal-aloe-grooming-wipes-1',
    verifiedDescription: 'Oatmeal and aloe grooming wipes for cleaning the coat and skin between baths.',
    verifiedIngredients: earthbathOatmealWipesIngredients,
    verifiedDirections: 'Remove one wipe, wipe the pet, close the lid tightly, store in a cool dry place, and do not flush the wipe.',
    verifiedWarnings: ['Avoid eye contact.', 'Flush with water if eye contact occurs.', 'Stop use and contact a veterinarian if irritation develops.'],
    ingredientsVerified: true, enrichmentStatus: 'verified', verificationSource: 'brand_page',
    availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt,
    sourceNote: 'Official Earthbath product page.', whyItFits: 'A real wipe option for routine dog grooming between baths.',
    whyCategoryFits: 'Grooming wipes fit routine surface cleaning and coat care.', cautions: 'Contains oat-derived ingredients and fragrance. Avoid the eyes and stop use if irritation appears.',
  },
  {
    id: 'purina-pro-plan-sensitive-skin-stomach-salmon-rice-dry', brand: 'Purina Pro Plan',
    name: 'Sensitive Skin & Stomach Salmon & Rice Formula Dog Food', category: 'food', subcategory: 'dry_food', species: ['dog'],
    shortDescription: 'Adult dry dog food made with salmon, rice, barley, and oat meal.', productTypeLabel: 'Sensitive stomach dry dog food',
    retailer: 'Purina', productUrl: 'https://www.purina.com/dogs/shop/pro-plan-specialized-nutrition-sensitive-skin-stomach-salmon-rice-dry-dog-food',
    recommendationKind: 'product', protein: 'Salmon', concernTags: ['sensitive_stomach', 'sensitive_skin', 'general_wellness'],
    excludedIngredients: ['fish', 'grains', 'beef'],
    avoidIngredientKeywords: ['salmon', 'fish', 'rice', 'barley', 'oat', 'beef fat', 'yeast'],
    ingredientHighlights: ['Salmon', 'Rice', 'Barley', 'Oat meal', 'Beef fat'], lifeStage: 'adult',
    tags: ['dog food', 'dry food', 'sensitive stomach', 'sensitive skin', 'salmon'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.purina.com/sites/default/files/product-label-deck-file/2023-01/4449-m444922-pro-plan-sensitive-skin-stomach-salmon-rice-formula-dog-food-dry-kk7.pdf',
    productPageUrl: 'https://www.purina.com/dogs/shop/pro-plan-specialized-nutrition-sensitive-skin-stomach-salmon-rice-dry-dog-food',
    verifiedProductPageUrl: 'https://www.purina.com/dogs/shop/pro-plan-specialized-nutrition-sensitive-skin-stomach-salmon-rice-dry-dog-food',
    labelUrl: 'https://www.purina.com/sites/default/files/product-label-deck-file/2023-01/4449-m444922-pro-plan-sensitive-skin-stomach-salmon-rice-formula-dog-food-dry-kk7.pdf',
    verifiedDescription: 'Salmon and rice dry formula for maintenance of adult dogs.',
    verifiedIngredients: purinaProPlanSensitiveDryIngredients,
    verifiedDirections: 'Use the feeding amounts as a starting point, adjust for age, activity, and environment, transition over 7 to 10 days, and provide fresh water daily.',
    verifiedWarnings: ['Adjust the amount to maintain ideal body condition.', 'See a veterinarian regularly for the pet health.'],
    ingredientsVerified: true, enrichmentStatus: 'verified', verificationSource: 'brand_page',
    availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt, sourceNote: 'Official Purina product label deck.',
    whyItFits: 'A real chicken-free dry food for adult dogs when the saved avoids permit fish, beef, and grains.',
    whyCategoryFits: 'Food is shown when nutrition or digestive context supports comparison.',
    cautions: 'Contains fish, beef fat, rice, barley, and oat meal. Transition foods gradually.',
  },
  {
    id: 'purina-pro-plan-sensitive-skin-stomach-salmon-rice-wet', brand: 'Purina Pro Plan',
    name: 'Sensitive Skin & Stomach Salmon & Rice Entree Classic Dog Food', category: 'food', subcategory: 'wet_food', species: ['dog'],
    shortDescription: 'Adult wet dog food with fish, salmon, rice, and oat meal.', productTypeLabel: 'Sensitive stomach wet dog food',
    retailer: 'Purina', productUrl: 'https://www.purina.com/dogs/shop/pro-plan-sensitive-skin-stomach-salmon-rice-wet-dog-food',
    recommendationKind: 'product', protein: 'Fish and salmon', concernTags: ['sensitive_stomach', 'sensitive_skin', 'general_wellness'],
    excludedIngredients: ['fish', 'grains'], avoidIngredientKeywords: ['fish', 'salmon', 'liver', 'rice', 'oat', 'corn oil'],
    ingredientHighlights: ['Fish', 'Liver', 'Salmon', 'Rice', 'Oat meal'], lifeStage: 'adult',
    tags: ['dog food', 'wet food', 'sensitive stomach', 'sensitive skin', 'salmon'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.purina.com/sites/default/files/product-label-deck-file/2023-06/4444-k444422-pro-plan-sensitive-skin-stomach-salmon-rice-entree-classic-dog-food-dd1.pdf',
    productPageUrl: 'https://www.purina.com/dogs/shop/pro-plan-sensitive-skin-stomach-salmon-rice-wet-dog-food',
    verifiedProductPageUrl: 'https://www.purina.com/dogs/shop/pro-plan-sensitive-skin-stomach-salmon-rice-wet-dog-food',
    labelUrl: 'https://www.purina.com/sites/default/files/product-label-deck-file/2023-06/4444-k444422-pro-plan-sensitive-skin-stomach-salmon-rice-entree-classic-dog-food-dd1.pdf',
    verifiedDescription: 'Salmon and rice wet formula for maintenance of adult dogs.',
    verifiedIngredients: purinaProPlanSensitiveWetIngredients,
    verifiedDirections: 'Divide the daily amount into two or more feedings and adjust the amount to maintain ideal body condition.',
    verifiedWarnings: ['Adjust the amount to maintain ideal body condition.', 'Review the current package label before feeding.'],
    ingredientsVerified: true, enrichmentStatus: 'verified', verificationSource: 'brand_page',
    availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt, sourceNote: 'Official Purina product label deck.',
    whyItFits: 'A real chicken-free wet food for adult dogs when the saved avoids permit fish and grains.',
    whyCategoryFits: 'Food is shown when nutrition or digestive context supports comparison.',
    cautions: 'Contains fish, liver, rice, oat meal, and corn oil. Adjust portions to maintain body condition.',
  },
  {
    id: 'greenies-original-teenie-dog-dental-treats', brand: 'Greenies',
    name: 'Original Teenie Natural Dental Dog Treats', category: 'health_essentials', subcategory: 'dental_treat', species: ['dog'],
    shortDescription: 'Daily dental chews sized for adult dogs weighing 5 to 15 lb.', productTypeLabel: 'Dog dental treats',
    retailer: 'Greenies', productUrl: 'https://www.greenies.com/products/treats/adult-dental-dog-treats-teenie-size-original',
    recommendationKind: 'product', protein: 'Poultry', concernTags: ['dental_care', 'general_wellness'],
    excludedIngredients: ['chicken', 'poultry', 'grains'],
    avoidIngredientKeywords: ['wheat', 'wheat gluten', 'gelatin', 'poultry', 'chicken'],
    ingredientHighlights: ['Wheat flour', 'Wheat gluten', 'Gelatin', 'Natural poultry flavor'], lifeStage: 'adult',
    tags: ['dental', 'dog', 'treat', 'chew', 'small dog', 'poultry', 'wheat'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.greenies.com/products/treats/adult-dental-dog-treats-teenie-size-original',
    verifiedProductPageUrl: 'https://www.greenies.com/products/treats/adult-dental-dog-treats-teenie-size-original',
    verifiedDescription: 'Original dental chew sized for adult dogs weighing 5 to 15 lb.',
    verifiedIngredients: greeniesOriginalRegularIngredients,
    verifiedDirections: 'Feed one dental treat per day to dogs 5 to 15 lb, provide fresh water, and reduce the main meal by the calories listed for the treat.',
    verifiedWarnings: ['Not suitable for dogs under 5 lb or under 6 months old.', 'Monitor the dog to make sure the treat is adequately chewed.', 'Choose the correct treat size for the dog weight.'],
    ingredientsVerified: true, enrichmentStatus: 'verified', verificationSource: 'brand_page',
    availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt, sourceNote: 'Official Greenies product page.',
    whyItFits: 'A real dental chew sized for small adult dogs.', whyCategoryFits: 'Dental treats fit routine dental wellness support.',
    cautions: 'Contains poultry and wheat. Choose the correct size and supervise chewing.',
  },
  {
    id: 'greenies-fresh-regular-dog-dental-treats', brand: 'Greenies',
    name: 'Fresh Regular Natural Dental Dog Treats', category: 'health_essentials', subcategory: 'dental_treat', species: ['dog'],
    shortDescription: 'Spearmint and peppermint dental chews for adult dogs weighing 25 to 50 lb.', productTypeLabel: 'Dog dental treats',
    retailer: 'Greenies', productUrl: 'https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-fresh-flavor',
    recommendationKind: 'product', protein: 'Not specified', concernTags: ['dental_care', 'general_wellness'],
    excludedIngredients: ['grains'], avoidIngredientKeywords: ['wheat', 'wheat gluten', 'gelatin', 'spearmint', 'peppermint'],
    ingredientHighlights: ['Wheat flour', 'Wheat gluten', 'Gelatin', 'Spearmint', 'Peppermint flavor'], lifeStage: 'adult',
    tags: ['dental', 'dog', 'treat', 'chew', 'fresh breath', 'wheat'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-fresh-flavor',
    verifiedProductPageUrl: 'https://www.greenies.com/products/treats/adult-dental-dog-treats-regular-size-fresh-flavor',
    verifiedDescription: 'Fresh-flavor dental chew sized for adult dogs weighing 25 to 50 lb.',
    verifiedIngredients: greeniesFreshRegularIngredients,
    verifiedDirections: 'Feed one dental treat per day to dogs 25 to 50 lb and provide fresh drinking water.',
    verifiedWarnings: ['Not suitable for dogs under 5 lb or under 6 months old.', 'Monitor the dog to make sure the treat is adequately chewed.', 'Choose the correct treat size for the dog weight.'],
    ingredientsVerified: true, enrichmentStatus: 'verified', verificationSource: 'brand_page',
    availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt, sourceNote: 'Official Greenies product page.',
    whyItFits: 'A real daily dental chew for medium adult dogs.', whyCategoryFits: 'Dental treats fit routine dental wellness support.',
    cautions: 'Contains wheat and gelatin. Choose the correct size and supervise chewing.',
  },
  {
    id: 'furminator-medium-dog-short-hair-deshedding-tool', brand: 'FURminator', name: 'Undercoat deShedding Tool Medium Dog Short Hair',
    category: 'grooming', subcategory: 'deshedding_tool', species: ['dog'], shortDescription: 'Undercoat deShedding tool for short-haired dogs weighing 25 to 50 lb.',
    productTypeLabel: 'Dog deShedding tool', retailer: 'FURminator',
    productUrl: 'https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-medium-dog-short-hair', recommendationKind: 'product',
    protein: 'Not applicable', concernTags: ['grooming', 'general_wellness'], excludedIngredients: [], avoidIngredientKeywords: [], ingredientHighlights: [],
    lifeStage: 'all', tags: ['grooming', 'dog', 'brush', 'deshedding', 'short hair', 'coat tool'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-medium-dog-short-hair',
    verifiedProductPageUrl: 'https://www.furminator.com/products/tools/deshedding-tools/undercoat-deshedding-tool-medium-dog-short-hair',
    verifiedDescription: 'Undercoat deShedding tool with a stainless steel edge, curved skin guard, ergonomic handle, and hair-release button.',
    verifiedDirections: 'Use on a dry coat after removing tangles or mats, then stroke gently in the direction of hair growth with extra care near sensitive areas.',
    verifiedWarnings: ['Inspect for sores, bruises, or skin conditions before use.', 'Avoid excessive pressure or repeated strokes in one area.', 'Stop use if redness or irritation appears.'],
    ingredientsVerified: false, enrichmentStatus: 'partial', verificationSource: 'brand_page', availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt,
    sourceNote: 'Official FURminator product page.', whyItFits: 'A real grooming tool for routine undercoat care.',
    whyCategoryFits: 'A deShedding tool fits routine coat care.', cautions: 'Use gently and do not use over irritated or wounded skin.',
  },
  {
    id: 'furminator-grooming-rake', brand: 'FURminator', name: 'Grooming Rake for Dogs and Cats', category: 'grooming', subcategory: 'rake', species: ['dog', 'cat'],
    shortDescription: 'Rotating-tooth grooming rake for pets with thick fur.', productTypeLabel: 'Pet grooming rake', retailer: 'FURminator',
    productUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/grooming-rake', recommendationKind: 'product',
    protein: 'Not applicable', concernTags: ['grooming', 'general_wellness'], excludedIngredients: [], avoidIngredientKeywords: [], ingredientHighlights: [],
    lifeStage: 'all', tags: ['grooming', 'dog', 'cat', 'rake', 'brush', 'thick fur', 'coat tool'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/grooming-rake',
    verifiedProductPageUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/grooming-rake',
    verifiedDescription: 'Grooming rake with rotating metal teeth for removing loose undercoat hair from dogs and cats with thicker fur.',
    verifiedDirections: 'Stroke gently in the direction of hair growth, starting at the head and using extra care near the stomach, legs, genitals, and anus.',
    verifiedWarnings: ['Inspect for sores, bruises, or skin conditions before use.', 'Avoid excessive strokes in one area.', 'Seek veterinary care before brushing over a skin condition.'],
    ingredientsVerified: false, enrichmentStatus: 'partial', verificationSource: 'brand_page', availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt,
    sourceNote: 'Official FURminator product page.', whyItFits: 'A real rake for routine thick-coat grooming.', whyCategoryFits: 'A grooming rake fits routine undercoat care.',
    cautions: 'Use gently and stop if the pet shows discomfort or skin irritation.',
  },
  {
    id: 'furminator-nail-grinder', brand: 'FURminator', name: 'Nail Grinder', category: 'grooming', subcategory: 'nail_tool', species: ['dog', 'cat'],
    shortDescription: 'Two-speed cordless nail grinder for dogs and cats.', productTypeLabel: 'Pet nail grinder', retailer: 'FURminator',
    productUrl: 'https://www.furminator.com/products/tools/nail-care/nail-grinder', recommendationKind: 'product',
    protein: 'Not applicable', concernTags: ['grooming', 'general_wellness'], excludedIngredients: [], avoidIngredientKeywords: [], ingredientHighlights: [],
    lifeStage: 'all', tags: ['grooming', 'dog', 'cat', 'nail grinder', 'nail care', 'tool'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.furminator.com/products/tools/nail-care/nail-grinder', verifiedProductPageUrl: 'https://www.furminator.com/products/tools/nail-care/nail-grinder',
    verifiedDescription: 'Two-speed cordless nail grinder with a built-in light, two grinding bands, and four AA batteries.',
    verifiedDirections: 'Introduce the sound gradually, identify the quick, hold the paw firmly, and use short passes while stopping before the quick.',
    verifiedWarnings: ['Stop before reaching the quick to avoid bleeding.', 'Use short passes to avoid overheating the nail.', 'Use only as directed.'],
    ingredientsVerified: false, enrichmentStatus: 'partial', verificationSource: 'brand_page', availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt,
    sourceNote: 'Official FURminator product page.', whyItFits: 'A real powered tool for routine pet nail care.', whyCategoryFits: 'Nail tools fit routine grooming.',
    cautions: 'Work slowly and stop before the quick. Ask a groomer or veterinarian for help when nail anatomy is unclear.',
  },
  {
    id: 'furminator-nail-clippers', brand: 'FURminator', name: 'Dog Nail Clippers', category: 'grooming', subcategory: 'nail_tool', species: ['dog'],
    shortDescription: 'Stainless steel nail clippers with an adjustable cutting guide.', productTypeLabel: 'Pet nail clippers', retailer: 'FURminator',
    productUrl: 'https://www.furminator.com/products/tools/nail-care/nail-clippers', recommendationKind: 'product', protein: 'Not applicable',
    concernTags: ['grooming', 'general_wellness'], excludedIngredients: [], avoidIngredientKeywords: [], ingredientHighlights: [],
    lifeStage: 'all', tags: ['grooming', 'dog', 'nail clippers', 'nail care', 'tool'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.furminator.com/products/tools/nail-care/nail-clippers', verifiedProductPageUrl: 'https://www.furminator.com/products/tools/nail-care/nail-clippers',
    verifiedDescription: 'Pet nail clippers with stainless steel cutting edges, easy-grip handles, and an adjustable cutting guide.',
    verifiedDirections: 'Monitor nail length, identify the quick, hold the paw firmly, and trim only the dead end of the nail.',
    verifiedWarnings: ['Stop before reaching the quick to avoid bleeding.', 'Use only as directed.', 'Ask a groomer or veterinarian for help when nail anatomy is unclear.'],
    ingredientsVerified: false, enrichmentStatus: 'partial', verificationSource: 'brand_page', availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt,
    sourceNote: 'Official FURminator product page.', whyItFits: 'A real manual tool for routine pet nail care.', whyCategoryFits: 'Nail tools fit routine grooming.',
    cautions: 'Trim conservatively and stop before the quick.',
  },
  {
    id: 'furminator-large-soft-slicker-brush', brand: 'FURminator', name: 'Large Soft Slicker Brush', category: 'grooming', subcategory: 'brush', species: ['dog', 'cat'],
    shortDescription: 'Soft slicker brush for pets with silky or wiry coats.', productTypeLabel: 'Pet slicker brush', retailer: 'FURminator',
    productUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/large-soft-slicker-brush', recommendationKind: 'product', protein: 'Not applicable',
    concernTags: ['grooming', 'general_wellness'], excludedIngredients: [], avoidIngredientKeywords: [], ingredientHighlights: [],
    lifeStage: 'all', tags: ['grooming', 'dog', 'cat', 'brush', 'slicker brush', 'silky coat', 'wiry coat'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/large-soft-slicker-brush',
    verifiedProductPageUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/large-soft-slicker-brush',
    verifiedDescription: 'Soft grooming slicker brush with a dual flex head, stainless steel bristles, and an ergonomic handle.',
    verifiedDirections: 'Use short smooth strokes in the direction of hair growth, beginning at the head and paying attention behind the ears and under the legs.',
    verifiedWarnings: ['Inspect for sores, bruises, or skin conditions before use.', 'Do not brush over a skin condition before seeking veterinary care.', 'Stop if irritation appears.'],
    ingredientsVerified: false, enrichmentStatus: 'partial', verificationSource: 'brand_page', availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt,
    sourceNote: 'Official FURminator product page.', whyItFits: 'A real slicker brush for routine coat detangling.', whyCategoryFits: 'Brushes fit routine coat care.',
    cautions: 'Use short gentle strokes and avoid irritated or wounded skin.',
  },
  {
    id: 'furminator-large-firm-slicker-brush', brand: 'FURminator', name: 'Large Firm Slicker Brush', category: 'grooming', subcategory: 'brush', species: ['dog', 'cat'],
    shortDescription: 'Firm slicker brush for pets with curly, long, or medium coats.', productTypeLabel: 'Pet slicker brush', retailer: 'FURminator',
    productUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/large-firm-slicker-brush', recommendationKind: 'product', protein: 'Not applicable',
    concernTags: ['grooming', 'general_wellness'], excludedIngredients: [], avoidIngredientKeywords: [], ingredientHighlights: [],
    lifeStage: 'all', tags: ['grooming', 'dog', 'cat', 'brush', 'slicker brush', 'curly coat', 'long coat'], currency: 'USD', active: true,
    source: 'curated', sourceUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/large-firm-slicker-brush',
    verifiedProductPageUrl: 'https://www.furminator.com/products/brush/brushes-and-rakes/large-firm-slicker-brush',
    verifiedDescription: 'Firm grooming slicker brush with a dual flex head, stainless steel bristles, and an ergonomic handle.',
    verifiedDirections: 'Use short smooth strokes in the direction of hair growth, beginning at the head and paying attention behind the ears and under the legs.',
    verifiedWarnings: ['Inspect for sores, bruises, or skin conditions before use.', 'Do not brush over a skin condition before seeking veterinary care.', 'Stop if irritation appears.'],
    ingredientsVerified: false, enrichmentStatus: 'partial', verificationSource: 'brand_page', availableCountries: ['US'], evidenceType: 'curated_static', lastVerifiedAt,
    sourceNote: 'Official FURminator product page.', whyItFits: 'A real slicker brush for routine coat detangling.', whyCategoryFits: 'Brushes fit routine coat care.',
    cautions: 'Use short gentle strokes and avoid irritated or wounded skin.',
  },
];

